6scode/Controllers/AdminAccountController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using System.Web;
using System.Web.Security;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using Microsoft.Owin.Security;
using System.Data;
using System.Collections;
using SkyDal;
using SkyEntity;
using SkyCommon;

namespace _6scode.Controllers
{
     [AllowAnonymous]
    public class AdminAccountController : Controller
    {
        private SkyWebContext db = new SkyWebContext();

        //
        // GET: /Account/
        public ActionResult Login()
        {
            FormsAuthentication.SignOut();
            if (!string.IsNullOrEmpty(Request["returnUrl"]))
            {

                ViewBag.returnUrl = Request["returnUrl"].ToString();
                ViewBag.msg = "对不起，您尚未登陆不允许访问！";

            }

            return View();
        }

        public ActionResult Logout()
        {
            FormsAuthentication.SignOut();
            Response.Cookies["uname"].Expires = DateTime.Now.AddDays(-1);
            Response.Cookies["uid"].Expires = DateTime.Now.AddDays(-1);
            System.Web.HttpContext.Current.Session["uid"] = null;
            System.Web.HttpContext.Current.Session["uname"] = null;
            return View("Login");
        }
        [HttpPost]
        public ActionResult Login(FormCollection fc)
        {
            System.Web.HttpContext.Current.Session["uname"] = "";
            string username = fc["UserName"];
            string password = CommonTools.ToMd5(fc["Password"].ToString());
            bool rememberme = fc["RememberMe"] == null ? false : true;
            string reurnUrl = fc["ReturnUrl"];




            var sysUsers = from s in db.SysUsers
                           orderby s.SysUserId ascending
                           where (s.SysUserName == username && (s.SysPassword == password))
                           select s;
            if (sysUsers.Count() > 0)
            {
                if (sysUsers.First().SysStatus)
                {
                    HttpCookie cookie = new HttpCookie("uname");
                    cookie.Value = username;
                    System.Web.HttpContext.Current.Response.Cookies.Add(cookie);

                    HttpCookie cookieid = new HttpCookie("uid");
                    cookieid.Value = sysUsers.First().SysUserId.ToString();
                    System.Web.HttpContext.Current.Response.Cookies.Add(cookieid);

                    System.Web.HttpContext.Current.Session["uid"] = sysUsers.First().SysUserId.ToString();
                    System.Web.HttpContext.Current.Session["uname"] = username;

                    FormsAuthentication.SetAuthCookie(username, rememberme);

                    if (string.IsNullOrEmpty(reurnUrl))
                    {
                        return RedirectToAction("Index","Admin");
                    }
                    else
                    {
                        System.Web.HttpContext.Current.Session["uname"] = null;
                        ViewBag.msg = "没有权限";
                        return Redirect(reurnUrl);
                    }

                }

                else
                {
                    System.Web.HttpContext.Current.Session["uname"] = null;
                    ViewBag.msg = "此已经被禁用，不允许登陆";
                    return View();

                }

            }
            else
            {
                System.Web.HttpContext.Current.Session["uname"] = null;
                ViewBag.msg = "用户名或密码错误了";
                return View();

            }


        }
	}
}

6scode/Controllers/AdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PagedList;
using PagedList.Mvc;
using SkyDal;
using SkyEntity;
using SkyService;
using SkyCommon;

namespace _6scode.Controllers
{
    public class AdminController : AdminBaseController
    {
        private UnitOfWork unitOfWork = new UnitOfWork();

        public ActionResult Index()
        {           
                return View();
           
        }

      
       
    }
}

6scode/Controllers/AdminSysUserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PagedList;
using PagedList.Mvc;
using SkyDal;
using SkyEntity;
using SkyCommon;


namespace _6scode.Controllers
{
    public class AdminSysUserController : AdminBaseController
    {
        private UnitOfWork unitOfWork = new UnitOfWork();

        public ActionResult Index(int? page)
        {
            Pager pager = new Pager();
            pager.table = "SysUser";
            pager.strwhere = "1=1";
            pager.PageSize = 2;
            pager.PageNo = page ?? 1;
            pager.FieldKey = "SysUserId";
            pager.FiledOrder = "SysUserId desc";

            pager = CommonDal.GetPager(pager);
            IList<SysUser> userList = DataConvertHelper<SysUser>.ConvertToModel(pager.EntityDataTable);
            var sysUsersAsIPageList = new StaticPagedList<SysUser>(userList, pager.PageNo, pager.PageSize, pager.Amount);
            return View(sysUsersAsIPageList);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public JsonResult UpdateStatus(int? id, bool status)
        {
            Message msg = new Message();
            if (id == null)
            {
                msg.MessageStatus = "false";
                msg.MessageInfo = "找不到ID";
            }
            SysUser sysuser = unitOfWork.sysUsersRepository.GetByID(id);
            sysuser.SysStatus = status;
            if (ModelState.IsValid)
            {

                unitOfWork.sysUsersRepository.Update(sysuser);
                unitOfWork.Save();
                msg.MessageStatus = "true";
                msg.MessageInfo = "已经更改为" + sysuser.SysStatus.ToString();
            }
            return Json(msg, JsonRequestBehavior.AllowGet);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public JsonResult ResetPassword(int id)
        {
            Message msg = new Message();

            SysUser sysuser = unitOfWork.sysUsersRepository.GetByID(id);
            string password = CommonTools.GenerateRandomNumber(8);
            string confirmpassword = CommonTools.ToMd5(password);
            string sysemail = sysuser.SysEmail;
            sysuser.SysPassword = confirmpassword;




            if (ModelState.IsValid)
            {

                unitOfWork.sysUsersRepository.Update(sysuser);
                unitOfWork.Save();
                string EmailContent = "密码已经被重置为" + password.ToString() + "，并已经发送邮件到" + sysuser.SysEmail + ",请注意查收！";
                EmailServer server = new EmailServer();
                Setting setting = unitOfWork.settingsRepository.GetByID(1);
                server.EmailAddress = setting.EmailFrom;
                server.EmailPassword = setting.EmailPassword;
                server.SMTPClient = setting.EmailHost;
                EmailEntity mailEntity = new EmailEntity();
                mailEntity.DisplayName = "6SCoder";
                mailEntity.MailContent = EmailContent;
                mailEntity.ToMail = sysemail;
                mailEntity.MailTitle = "重置密码邮件";
                mailEntity.FromMail = server.EmailAddress;
                EmailServices.SendEmail(server, mailEntity);

                msg.MessageStatus = "true";
                msg.MessageInfo = EmailContent;
            }
            return Json(msg, JsonRequestBehavior.AllowGet);
        }


        // POST: /SysUser/Create
        // 为了防止“过多发布”攻击，请启用要绑定到的特定属性，有关 
        // 详细信息，请参阅 http://go.microsoft.com/fwlink/?LinkId=317598。
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "SysUserId,SysUserName,SysPassword,SysEmail,SysStatus")] SysUser sysuser)
        {
            if (ModelState.IsValid)
            {
                sysuser.SysPassword = CommonTools.ToMd5(sysuser.SysPassword);
                unitOfWork.sysUsersRepository.Insert(sysuser);
                unitOfWork.Save();
                return RedirectToAction("Index");
            }

            return View(sysuser);
        }




        [HttpPost]
        [ValidateAntiForgeryToken]
        public JsonResult DeleteConfirmed(int? id)
        {
            Message msg = new Message();
            if (id == null)
            {
                msg.MessageStatus = "false";
                msg.MessageInfo = "找不到ID";
            }
            else
            {

                unitOfWork.sysUsersRepository.Delete(id);
                unitOfWork.Save();

                msg.MessageStatus = "true";
                msg.MessageInfo = "删除成功";
            }

            return Json(msg, JsonRequestBehavior.AllowGet);
        }

	}
}

6scode/Controllers/CourseListController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PagedList;
using PagedList.Mvc;
using SkyDal;
using SkyEntity;
using SkyService;
using SkyCommon;

namespace _6scode.Controllers
{
    public class CourseListController : HomeBaseController
    {
        private UnitOfWork unitOfWork = new UnitOfWork();

        public ActionResult CourseList(int? page, int cid)
        {

            Pager pager = new Pager();
            pager.table = "VideoCourse";
            pager.strwhere = "Category=" + cid;
            pager.PageSize = 2;
            pager.PageNo = page ?? 1;
            pager.FieldKey = "Id";
            pager.FiledOrder = "Paixu asc";
            pager = CommonDal.GetPager(pager);
            IList<VideoCourse> dataList = DataConvertHelper<VideoCourse>.ConvertToModel(pager.EntityDataTable);
            var PageList = new StaticPagedList<VideoCourse>(dataList, pager.PageNo, pager.PageSize, pager.Amount);
            return View(PageList);

        }
        //
        // GET: /CourseList/
        public ActionResult Content(int id)
        {

            VideoCourse videoCourse = unitOfWork.videoCoursesRepository.GetByID(id);

            if (videoCourse == null)
            {
                return HttpNotFound();
            }
            return View(videoCourse);
        }

	}
}

6scode/Controllers/UserAccountController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using System.Web;
using System.Web.Security;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using Microsoft.Owin.Security;
using System.Data;
using System.Collections;
using SkyDal;
using SkyEntity;
using SkyCommon;

namespace _6scode.Controllers
{
     [AllowAnonymous]
    public class UserAccountController : Controller
    {
        private SkyWebContext db = new SkyWebContext();

        //
        // GET: /Account/
        public ActionResult Login()
        {

            if (!string.IsNullOrEmpty(Request["returnUrl"]))
            {

                ViewBag.returnUrl = Request["returnUrl"].ToString();
                ViewBag.msg = "对不起，您尚未登陆不允许访问！";

            }

            return View();
        }

        public ActionResult Logout()
        {

            Response.Cookies["codername"].Expires = DateTime.Now.AddDays(-1);
            Response.Cookies["coderid"].Expires = DateTime.Now.AddDays(-1);
            System.Web.HttpContext.Current.Session["coderid"] = null;
            System.Web.HttpContext.Current.Session["codername"] = null;
            return View("Login");
        }
        [HttpPost]
        public ActionResult Login(FormCollection fc)
        {
            System.Web.HttpContext.Current.Session["codername"] = "";
            string username = fc["UserName"];
            string password = CommonTools.ToMd5(fc["Password"].ToString());
            bool rememberme = fc["RememberMe"] == null ? false : true;
            string reurnUrl = fc["ReturnUrl"];




            var codeUsers = from s in db.CodeUsers
                           orderby s.Id ascending
                           where (s.UserName == username && s.Password == password)
                           select s;
            if (codeUsers.Count() > 0)
            {
                if (codeUsers.First().UserStatus)
                {
                    HttpCookie cookie = new HttpCookie("codername");
                    cookie.Value = username;
                    System.Web.HttpContext.Current.Response.Cookies.Add(cookie);

                    HttpCookie cookieid = new HttpCookie("coderid");
                    cookieid.Value = codeUsers.First().UserStatus.ToString();
                    System.Web.HttpContext.Current.Response.Cookies.Add(cookieid);

                    System.Web.HttpContext.Current.Session["coderid"] = codeUsers.First().Id.ToString();
                    System.Web.HttpContext.Current.Session["codername"] = username;

                    FormsAuthentication.SetAuthCookie(username, rememberme);

                    if (string.IsNullOrEmpty(reurnUrl))
                    {
                        return RedirectToAction("Index","Home");
                    }
                    else
                    {
                        System.Web.HttpContext.Current.Session["codername"] = null;
                        ViewBag.msg = "没有权限";
                        return Redirect(reurnUrl);
                    }

                }

                else
                {
                    System.Web.HttpContext.Current.Session["codername"] = null;
                    ViewBag.msg = "此已经被禁用，不允许登陆";
                    return View();

                }

            }
            else
            {
                System.Web.HttpContext.Current.Session["codername"] = null;
                ViewBag.msg = "用户名或密码错误了";
                return View();

            }


        }
	}
}

6scode/Views/Shared/CourseList.cshtml
@model StaticPagedList<SkyEntity.VideoCourse>
@using PagedList;
@using PagedList.Mvc;
@using SkyService;
@{
    ViewBag.title = "课程管理";
}

<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <h1>
            Scratch零基础入门课
            <small>本课程内容共8节，建议你按照顺序学习。</small>
        </h1>
        <ol class="breadcrumb">
            <li><a href="#"><i class="fa fa-dashboard"></i> 首页</a></li>
            <li class="active">课程中心</li>
        </ol>
    </section>
    <!-- Main content -->
    <section class="content">

        <div class="row">

@foreach (var item in Model)
                                {
            <div class="col-md-4 col-sm-6 col-xs-12">
                <div class="info-box">
                    <span class="info-box-icon bg-green">@item.Paixu</span>
                    <div class="info-box-content">

                        <span class="info-box-number"><a href="@Url.Action("Content", "VideoCourse", new { id=item.Id})">@item.Title</a></span>
                        <span class="info-box-text text-gray">@item.Info</span>
                    </div>
                    <!-- /.info-box-content -->
                </div>
                <!-- /.info-box -->
            </div>

}

          



        </div>


    </section>
    <!-- /.content -->
</div>

6scode/Views/Shared/_AdminMenuPartial.cshtml
<section class="sidebar">
    <!-- Sidebar user panel (optional) -->
    <div class="user-panel">
        <div class="pull-left image">
            <img src="/dist/img/user2-160x160.jpg" class="img-circle" alt="User Image">
        </div>
        <div class="pull-left info">
            <p>赵艺涵</p>
            <!-- Status -->
            <a href="#"><i class="fa fa-circle text-success"></i>女 8岁</a>
        </div>
    </div>

    <!-- /.search form -->
    <!-- Sidebar Menu -->
    <ul class="sidebar-menu">
        <li class="header">6S少儿编程学习系统</li>
        <!-- Optionally, you can add icons to the links -->
        <li><a href="@Url.Action("Index","Admin")"><i class="fa fa-dashboard"></i> <span>仪表盘</span></a></li>
        <li><a href="@Url.Action("Index","VideoCourse")"><i class="fa fa-table"></i> <span>课程管理</span></a></li>
        <li><a href="@Url.Action("Index","CodeUser")"><i class="fa fa-table"></i> <span>用户管理</span></a></li>

        <li class="treeview">
            <a href="#">
                <i class="fa fa-cog"></i> <span>系统设置</span>
                <span class="pull-right-container">
                    <i class="fa fa-cog pull-right"></i>
                </span>
            </a>
            <ul class="treeview-menu">               
                <li><a href="@Url.Action("Index","AdminSysUser")">系统用户</a></li>
                <li><a href="@Url.Action("Index","Category")">分类设置</a></li>
                <li><a href="@Url.Action("Index","AdminSetting")">系统设置</a></li>
            </ul>
        </li>
        <li><a href="@Url.Action("Logout", "AdminAccount")"><i class="fa  fa-dot-circle-o"></i> <span>退出</span></a></li>
    </ul>
    <!-- /.sidebar-menu -->
</section>

6scode/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>@ViewBag.Title -6S少儿编程</title>
    <!-- Tell the browser to be responsive to screen width -->
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <!-- Bootstrap 3.3.6 -->
    <link rel="stylesheet" href="/bootstrap/css/bootstrap.min.css">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.5.0/css/font-awesome.min.css">
    <!-- Ionicons -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/ionicons/2.0.1/css/ionicons.min.css">
    <!-- Theme style -->
    <link rel="stylesheet" href="/dist/css/AdminLTE.css">
    <!-- AdminLTE Skins. We have chosen the skin-blue for this starter
          page. However, you can choose any other skin. Make sure you
          apply the skin class to the body tag so the changes take effect.
    -->
    <link rel="stylesheet" href="/dist/css/skins/skin-blue.min.css">
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
    @RenderSection("TopCss", required: false)
    @RenderSection("TopScripts", required: false)
</head>

<body class="hold-transition skin-blue sidebar-mini">
    <div class="wrapper">
        <!-- Main Header -->
    
        @Html.Partial("_TopPartial")

        <!-- Left side column. contains the logo and sidebar -->
        <aside class="main-sidebar">
            <!-- sidebar: style can be found in sidebar.less -->

            @Html.Partial("_MenuPartial")

            <!-- /.sidebar -->
        </aside>
        <!-- Content Wrapper. Contains page content -->
       

            @RenderBody()


        <!-- /.content-wrapper -->
        <!-- Main Footer -->
        <footer class="main-footer">
            <!-- To the right -->
            <div class="pull-right hidden-xs">
                有问题找奕鸥老师，微信：sky20100
            </div>
            <!-- Default to the left -->
            <strong>Copyright &copy; 2009-2019 <a href="#">6S少儿编程</a>.</strong> All rights reserved.
        </footer>
        <!-- Control Sidebar -->
        
        <!-- /.control-sidebar -->
        <!-- Add the sidebar's background. This div must be placed
             immediately after the control sidebar -->
        <div class="control-sidebar-bg"></div>
    </div>
    <!-- ./wrapper -->
    <!-- REQUIRED JS SCRIPTS -->
    <!-- jQuery 2.2.3 -->
    <script src="/plugins/jQuery/jquery-2.2.3.min.js"></script>
    <!-- Bootstrap 3.3.6 -->
    <script src="/bootstrap/js/bootstrap.min.js"></script>
    <!-- AdminLTE App -->
    <script src="/dist/js/app.min.js"></script>
    <script src="/Resource/js/SkyWeb.js"></script>
    <!-- Optionally, you can add Slimscroll and FastClick plugins.
         Both of these plugins are recommended to enhance the
         user experience. Slimscroll is required when using the
         fixed layout. -->
    @RenderSection("BottomScripts", required: false)
    <script type="text/javascript">
        var url = GetUrl('pathname') + GetUrl('search');
        url = getStrPre(url, "&");

        $('.sidebar-menu li a').each(function () {

            var hrefurl = $(this).attr('href');

            if (url == hrefurl) {
                $(this).parent().addClass('active');
                // alert($(this).parent().parent().parent().text());

                if ($(this).parent().parent().parent().hasClass('treeview')) {
                    $(this).parent().parent().parent().addClass('active');
                }
            }
        }
            );
    </script>
</body>
</html>

6scode/Views/Shared/_LayoutAdmin.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>@ViewBag.Title -6S少儿编程</title>
    <!-- Tell the browser to be responsive to screen width -->
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <!-- Bootstrap 3.3.6 -->
    <link rel="stylesheet" href="/bootstrap/css/bootstrap.min.css">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.5.0/css/font-awesome.min.css">
    <!-- Ionicons -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/ionicons/2.0.1/css/ionicons.min.css">
    <!-- Theme style -->
    <link rel="stylesheet" href="/dist/css/AdminLTE.css">
    <!-- AdminLTE Skins. We have chosen the skin-blue for this starter
          page. However, you can choose any other skin. Make sure you
          apply the skin class to the body tag so the changes take effect.
    -->
    <link rel="stylesheet" href="/dist/css/skins/skin-blue.min.css">
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
    @RenderSection("TopCss", required: false)
    @RenderSection("TopScripts", required: false)
</head>

<body class="hold-transition skin-blue sidebar-mini">
    <div class="wrapper">
        <!-- Main Header -->
    
        @Html.Partial("_TopPartial")

        <!-- Left side column. contains the logo and sidebar -->
        <aside class="main-sidebar">
            <!-- sidebar: style can be found in sidebar.less -->

            @Html.Partial("_MenuPartial")

            <!-- /.sidebar -->
        </aside>
        <!-- Content Wrapper. Contains page content -->
       

            @RenderBody()


        <!-- /.content-wrapper -->
        <!-- Main Footer -->
        <footer class="main-footer">
            <!-- To the right -->
            <div class="pull-right hidden-xs">
                有问题找奕鸥老师，微信：sky20100
            </div>
            <!-- Default to the left -->
            <strong>Copyright &copy; 2009-2019 <a href="#">6S少儿编程</a>.</strong> All rights reserved.
        </footer>
        <!-- Control Sidebar -->
        
        <!-- /.control-sidebar -->
        <!-- Add the sidebar's background. This div must be placed
             immediately after the control sidebar -->
        <div class="control-sidebar-bg"></div>
    </div>
    <!-- ./wrapper -->
    <!-- REQUIRED JS SCRIPTS -->
    <!-- jQuery 2.2.3 -->
    <script src="/plugins/jQuery/jquery-2.2.3.min.js"></script>
    <!-- Bootstrap 3.3.6 -->
    <script src="/bootstrap/js/bootstrap.min.js"></script>
    <!-- AdminLTE App -->
    <script src="/dist/js/app.min.js"></script>
    <script src="/Resource/js/SkyWeb.js"></script>
    <!-- Optionally, you can add Slimscroll and FastClick plugins.
         Both of these plugins are recommended to enhance the
         user experience. Slimscroll is required when using the
         fixed layout. -->
    @RenderSection("BottomScripts", required: false)
    <script type="text/javascript">
        var url = GetUrl('pathname') + GetUrl('search');
        url = getStrPre(url, "&");

        $('.sidebar-menu li a').each(function () {

            var hrefurl = $(this).attr('href');

            if (url == hrefurl) {
                $(this).parent().addClass('active');
                // alert($(this).parent().parent().parent().text());

                if ($(this).parent().parent().parent().hasClass('treeview')) {
                    $(this).parent().parent().parent().addClass('active');
                }
            }
        }
            );
    </script>
</body>
</html>

6scode/Views/Shared/_MenuPartial.cshtml
<section class="sidebar">
    <!-- Sidebar user panel (optional) -->
    <div class="user-panel">
        <div class="pull-left image">
            <img src="/dist/img/user2-160x160.jpg" class="img-circle" alt="User Image">
        </div>
        <div class="pull-left info">
            <p>@Session["CoderName"]</p>
            <!-- Status -->
            @*<a href="#"><i class="fa fa-circle text-success"></i>女 8岁</a>*@
        </div>
    </div>

    <!-- /.search form -->
    <!-- Sidebar Menu -->
    <ul class="sidebar-menu">
        <li class="header">6S少儿编程学习系统</li>
        <!-- Optionally, you can add icons to the links -->
        <li><a href="@Url.Action("Index","Home")"><i class="fa fa-dashboard"></i> <span>仪表盘</span></a></li>
        <li><a href="@Url.Action("CourseCenter","Home")"><i class="fa fa-table"></i> <span>课程中心</span></a></li>
        <li><a href="http://naotu.baidu.com" target="_blank"><i class="fa fa-link"></i> <span>思维训练工具</span></a></li>
        <li><a href="http://lema.91xbc.com" target="_blank"><i class="fa fa-link"></i> <span>编程练习系统</span></a></li>
        <li><a href="@Url.Action("SetPassword","Home")"><i class="fa fa-cog"></i> <span>修改密码</span></a></li>
        <li><a href="@Url.Action("Logout", "UserAccount")"><i class="fa  fa-dot-circle-o"></i> <span>退出</span></a></li>
        
    </ul>
    <!-- /.sidebar-menu -->
</section>

6scode/Views/Shared/_TopPartial.cshtml
<header class="main-header">
    <!-- Logo -->
    <a href="index2.html" class="logo">
        <!-- mini logo for sidebar mini 50x50 pixels -->
        <span class="logo-mini"><b>6S</b></span>
        <!-- logo for regular state and mobile devices -->
        <span class="logo-lg"><b>6S</b>Code</span>
    </a>
    <!-- Header Navbar -->
    <nav class="navbar navbar-static-top" role="navigation">
        <!-- Sidebar toggle button-->
        <a href="#" class="sidebar-toggle" data-toggle="offcanvas" role="button">
            <span class="sr-only">Toggle navigation</span>
        </a>
        <!-- Navbar Right Menu -->
        
    </nav>
</header>